---
comments: false
date: "2021-06-01T10:00:00+00:00"
title: "Accessibility commitment"
---

Travel back to the [home page](/) or [about page](/about).

## Feedback

I welcome any feedback on the accessibility of my site and/or the educational materials I create. Please let me know if you encounter any accessibility barriers by using my [contact form](/contact) and I'll do my best to respond promptly.

Thank you for visiting my site and for taking the time to read this page {{< bi heart-fill >}}

## Accessibility practices

This site has been designed with the following features in mind:

- A color palette that meets WCAG 2.1 AA standards for contrast
- Alternative text for all informative images
- Readable font faces, specifically to avoid impostor letter shapes and mirroring. This site primarily uses Red Hat Text which is freely available and has been found to be relatively accessible to users with dyslexic traits and poor near vision.[^1]
- A table of contents in the blog post sidebar for easier navigation

I'm aware there is much more to inclusive and accessible design and I'm learning how to implement better accessibility practices in the content I create. I'm not a web developer but my plan is to regularly audit my site for accessibility failures and learn how to remedy them as best I can. I'll be using the following evaluation tools:

- [WAVE Web Accessibility Evaluation Tool](https://wave.webaim.org/)

In addition, I'll document the failures and any corrective actions as issues in the [GitHub repository](https://github.com/spcanelon/silvia/issues) housing the files used to build this site.

## Work related to accessibility

- Talk: [Revealing Room for Improvement in Accessibility within a Social Media Data Visualization Learning Community](/talk/2021-05-04-data-viz-accessibility/)
- Blog post: [Resources for Data Viz Accessibility](/blog/2021-09-23-data-viz-a11y/)
- Blog post: [Auditing for Web Accessibility](/blog/2021-06-02-wave-audit-1/)

[^1]: For more on font accessibility, I recommend the talk [Don't Believe the Type!](https://youtu.be/h8IOqUl1zII?t=1029) by [The Readability Group](https://medium.com/the-readability-group).
