---
title: Becoming certified as an RStudio Tidyverse Instructor
author: silvia
date: '2020-10-05'
slug: rstudio-instructor-certification-tidyverse
categories:
  - R
tags:
  - r
  - tidyverse
subtitle: "An account of my experience on this journey and resources to help others on theirs."
summary: "An account of my experience on this journey and resources to help others on theirs."
authors: []
lastmod: '2020-10-05T13:55:03-04:00'
featured: yes
draft: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

# Why did I get trained?

Teaching R was not something I thought I'd ever get into when I started using R for my postdoc position. I had taken programming courses as an undergraduate student and still found myself hiking up a learning curve. My learning came primarily from code chunks from coworkers, StackOverflow, and the as-needed browsing of [R for Data Science](https://r4ds.had.co.nz/). This approach was _ok_ and served me to get where I needed to go for work projects, but it wasn't methodical by any stretch of the imagination.

Meanwhile, [CHOP R User group](https://education.arcus.chop.edu/user-groups/) lunch-and-learns and [R-Ladies Philly](https://www.rladiesphilly.org/) meet-ups were showing me the robustness and versatility of R across disciplines and it quickly became clear there were very tangible ways I could use these skills to support a community organizing collective that I'm a part of. This would require teaching R to folks that don't program and have very little, if any, experience handling data. I didn't feel prepared to take this on knowing I had hiked down learning paths that I wouldn't necessarily recommend to others. 

Fast-forward and I can now say I feel prepared because the RStudio Instructor Training provided all the tools I need in order to take the next steps with my collective! 

Read on to find out what I learned before I decided to pursue the certification, what the certification experience was like for me, and resources to support you in your own journey if you decide to take this path.

