---
title: 'An Antarctic Tour of the Tidyverse'
author: silvia
date: 2020-08-31T17:40:00
categories:
  - R
tags:
  - R
  - tidyverse
subtitle: An introductory tidyverse tutorial created and presented for [R-Ladies Chicago](https://rladieschicago.org/)
summary: An introductory tidyverse tutorial created and presented for R-Ladies Chicago
slug: 2020-08-31-tour-of-the-tidyverse
draft: no
event: R-Ladies Chicago Meetup
event_url: https://www.meetup.com/rladies-chicago/events/272755101/
location: Chicago, IL, USA (virtual)
abstract: Learn how to explore and manipulate data in R with packages from the Tidyverse. We'll introduce the [8 core packages](https://www.tidyverse.org/packages/) that make up the Tidyverse and use at least one function from each package while exploring a dataset on the migration of penguins.
date_end: 2020-08-31T19:40:00
all_day: no
publishDate: '2020-09-01'
featured: yes
image: 
  caption: '[Antarctic Tour of the Tidyverse](https://spcanelon.github.io/tour-of-the-tidyverse)'
  focal_point: center
  preview_only: no
links:
- icon: images
  icon_pack: fas
  name: slides
  url: https://spcanelon.github.io/tour-of-the-tidyverse
- icon: play-circle
  icon_pack: fas
  name: video
  url: https://youtu.be/9yXZGN5yVF4
- icon: github
  icon_pack: fab
  name: materials
  url: https://github.com/spcanelon/tour-of-the-tidyverse#an-antarctic-tour-of-the-tidyverse
---

<!--xaringanExtra interferes with the social media preview-->

```{r setup, include=FALSE, eval=FALSE}
library(xaringanExtra)
```

```{r echo=FALSE, eval=FALSE}
xaringanExtra::embed_xaringan(
  url = "https://spcanelon.github.io/tour-of-the-tidyverse",
  ratio = "16:9")
```
