---
title: "A medication-wide association study (MWAS) on repurposed drugs for COVID-19 with Pre-pandemic prescription medication exposure and pregnancy outcomes"
author: 
- Lena Davidson
- name: Silvia P. Canelón
  orcid: 0000-0003-1709-1394
- Mary Regina Boland
date: '2022-11-24'
slug: mwas-repurposed-covid19-meds 
categories:
  - research
  - EHR
  - covid-19
  - pregnancy
  - medications
description: 'Scientific Reports'
# doi-title: Scientific Reports (DOI)
# doi: "10.1038/s41598-022-24218-1"
subtitle: EHR study describing an MWAS approach to explore connections between exposure to repurposed COVID-19 prescription medications and the risk of cesarean section, preterm birth, and stillbirth
links:
- icon: file-richtext-fill
  name: Publication
  url: https://doi.org/10.1038/s41598-022-24218-1
---

## Abstract

Information on effects of medication therapies during pregnancy is lacking as pregnant patients are often excluded from clinical trials. This retrospective study explores the potential of using electronic health record (EHR) data to inform safety profiles of repurposed COVID medication therapies on pregnancy outcomes using pre-COVID data. We conducted a medication-wide association study (MWAS) on prescription medication exposures during pregnancy and the risk of cesarean section, preterm birth, and stillbirth, using EHR data between 2010–2017 on deliveries at PennMedicine. Repurposed drugs studied for treatment of COVID-19 were extracted from ClinicalTrials.gov (n = 138). We adjusted for known comorbidities diagnosed within 2 years prior to birth. Using previously developed medication mapping and delivery-identification algorithms, we identified medication exposure in 2,830 of a total 63,334 deliveries; from 138 trials, we found 31 medications prescribed and included in our cohort. We found 21 (68%) of the 31 medications were not positively associated with increased risk of the outcomes examined. With caution, these medications warrant potential for inclusion of pregnant individuals in future studies, while drugs found to be associated with pregnancy outcomes require further investigation. MWAS facilitates hypothesis-driven evaluation of drug safety across all prescription medications, revealing potential drug candidates for further research.
