---
pagetitle: "Philly CCD Sips 2019 Map"
include-in-header: meta-map.html
format: 
  html:
    page-layout: custom
    embed-resources: true
---

```{r meta, include=FALSE}
library(metathis)

meta() %>%
  meta_general(
    description = "An interactive map showing restaurants participating in Philadelphia's CCD Sips 2019",
    generator = "quarto"
  ) %>% 
  meta_name("github-repo" = "spcanelon/silvia") %>% 
  # https://pkg.garrickadenbuie.com/metathis/reference/meta_viewport.html
  meta_viewport(width = "device-width",
                        initial_scale = "1.0",
                        maximum_scale = "1.0",
                        user_scalable = "no") %>% 
  # tags for social media
  meta_social(
    title = "Philly CCD Sips 2019 Interactive Map",
    url = "https://www.silviacanelon.com/blog/2019-ccd-sips/map.html",
    image = "https://github.com/spcanelon/silvia/blob/main/content/blog/2019-08-04-ccd-sips/featured.png?raw=true",
    image_alt = "Map of Philly's Center City with a pop-up saying Center City District Sips 2019",
    og_type = "website",
    og_author = "Silvia Canelón",
    twitter_card_type = "summary_large_image",
    twitter_creator = "@spcanelon"
  ) %>% 
  # https://pkg.garrickadenbuie.com/metathis/index.html
  # https://pkg.garrickadenbuie.com/metathis/reference/write_meta.html
  write_meta(path = "meta-map.html")
```

```{r include=FALSE}
xfun::pkg_attach("tidyverse", "here", "leaflet")

knitr::opts_chunk$set(echo = FALSE)
```

```{r}
sips <- read_rds(here("blog/2019-08-04-ccd-sips/sips.Rds"))
```

```{r}
# Create the pop-up information with inline css styling
popInfoCircles<-paste("<h2 style='border-bottom: thin dotted #43464C;
    padding-bottom:4px; margin-bottom:4px;
    font-family: Tahoma, Geneva, sans-serif;
    font-size: 1.6em;
    color:#43464C;'>", sips$Restaurant, "</h2>
    <p style=font-family: Tahoma, Geneva, sans-serif;
    font-size: 1.5em;
    color:#9197A6;'>", sips$Address, "</p>")

popInfoMarker<-paste("<h1 style='border-bottom: thin dotted #43464C;
    padding-bottom:4px; margin-bottom:4px;
    font-family: Tahoma, Geneva, sans-serif;
    font-size: 1.8em;
    color:#43464C;'>", "Center City District Sips 2019", "</h1>
    <p style='font-size: 1.5em; color:#9197A6;'>", "Philadelphia, PA", "<br>")

# Creating the map
leaflet(data = sips, width = "100%", height =  "850px") %>%
  addCircles(
    lat = ~ sips$Latitude, 
    lng = ~ sips$Longitude, 
    color = "olivedrab",
    fillOpacity=0.6, 
    radius=8, 
    popup = popInfoCircles,
    label = ~ Restaurant,
    labelOptions = labelOptions(
      style = list("font-family" = "Tahoma, Geneva, sans-serif",
                   "font-size" = "1.2em")
      )) %>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  setView(mean(sips$Longitude),
          mean(sips$Latitude), 
          zoom=17) %>%
  addMarkers(
    lng = mean(sips$Longitude), 
    lat = mean(sips$Latitude), 
    popup = popInfoMarker,
    label = "Center City District Sips 2019",
    labelOptions = labelOptions(
      style = list("font-family" = "Tahoma, Geneva, sans-serif",
                   "font-size" = "1.2em")
      )) %>% 
  leaflet.extras::addFullscreenControl()
```

