---
title: 'Philly Center City Sips 2019: An Interactive Map'
author: silvia
date: '2019-08-04'
slug: ccd-sips
categories: [R minis]
tags:
  - mapping
  - R
subtitle: 'An interactive map showing restaurants participating in Philly’s Center City District Sips 2019.'
summary: 'An interactive map showing restaurants participating in Philly’s Center City District Sips 2019.'
authors: []
lastmod: ''
featured: yes
image:
  caption: '[Image credit: Silvia Canelón](featured.png)'
  placement: 2
  focal_point: 'Center'
  preview_only: no
projects: []
links:
- icon: map-marked-alt
  icon_pack: fas
  name: Interactive Map
  url: https://spcanelon.github.io/CCDSips2019.html
---

I used **R** to play around with **webscraping** and create an [interactive map](https://spcanelon.github.io/CCDSips2019.html/) showing restaurants participating in Philly’s 2019 [Center City District Sips](https://centercityphila.org/explore-center-city/ccdsips). Center City Sips is a series of summer Wednesday evenings filled with **happy hour specials**.

This mini-project was motivated by two of my close friends' frustration with the website shortcomings. **The information was presented beautifully, but there was no map view**! This made it difficult to figure out what happy hours you could check out nearby.

The map pop-ups could use information on the specials for each restaurant, but my newly acquired skills with the `RSelenium` and `Leaflet` packages weren't quite up to the task! **Suggestions and advice are welcome!**

I haven't figured out how to fix the cute, but useless, baby `<iframe>` below but the link button at the top of the post will take you to a full screen version.


<iframe
    src="https://spcanelon.github.io/CCDSips2019.html">
    width= "1000px"
    height= "500px"
    style="border:none">
</iframe>
